package com.acaivis.service;
import com.acaivis.dto.*; import com.acaivis.exception.ResourceNotFoundException; import com.acaivis.model.*; import com.acaivis.repository.*; import org.springframework.data.domain.Page; import org.springframework.data.domain.Pageable; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.List;
@Service public class ProductService { private final ProductRepository repo; private final CategoryRepository cats; public ProductService(ProductRepository r,CategoryRepository c){repo=r;cats=c;}
 @Transactional public ProductResponse create(ProductRequest d){Product p=new Product(); apply(p,d); return toResponse(repo.save(p));}
 @Transactional(readOnly=true) public List<ProductResponse> findAll(boolean onlyAvailable){return (onlyAvailable?repo.findByAvailableTrue():repo.findAll()).stream().map(this::toResponse).toList();}
 @Transactional(readOnly=true) public ProductPageResponse findAdminPage(String search, Long categoryId, Boolean available, Pageable pageable){ String normalized=search==null?"":search.trim(); Page<Product> page=repo.findAdminProducts(normalized, categoryId, available, pageable); return new ProductPageResponse(page.getContent().stream().map(this::toResponse).toList(), page.getTotalElements(), page.getTotalPages(), page.getNumber(), page.getSize());}
 @Transactional public ProductResponse reactivate(Long id){ Product p=repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Produto não encontrado: "+id)); p.setAvailable(true); return toResponse(repo.save(p));}
 @Transactional(readOnly=true) public ProductResponse findById(Long id){return toResponse(repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Produto não encontrado: "+id)));}
 @Transactional public ProductResponse update(Long id,ProductRequest d){Product p=repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Produto não encontrado: "+id)); apply(p,d); return toResponse(repo.save(p));}
 @Transactional public void delete(Long id){Product p=repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Produto não encontrado: "+id));p.setAvailable(false);repo.save(p);}
 private void apply(Product p,ProductRequest d){Category c=cats.findById(d.categoryId()).orElseThrow(()->new ResourceNotFoundException("Categoria não encontrada: "+d.categoryId()));p.setName(d.name().trim());p.setSize(d.size().trim());p.setDescription(d.description().trim());p.setPrice(d.price());p.setImageUrl(d.imageUrl());p.setBadge(d.badge());p.setStockQuantity(d.stockQuantity());p.setAvailable(d.available());p.setCategory(c);}
 private ProductResponse toResponse(Product p){return new ProductResponse(p.getId(),p.getName(),p.getSize(),p.getDescription(),p.getPrice(),p.getImageUrl(),p.getBadge(),p.getStockQuantity(),p.isAvailable(),p.getCategory().getId(),p.getCategory().getName(),p.getCreatedAt(),p.getUpdatedAt());}}
