ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'ADMIN';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_route_order INTEGER;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_proof_url VARCHAR(1000);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_proof_path VARCHAR(500);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivered_by VARCHAR(255);
